"""Source-level guards for public-builder strict CEF qualification workflows."""
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class StrictQualificationWorkflowTests(unittest.TestCase):
    def test_full_platform_workflow_is_exact_and_keeps_native_output_private(self):
        text = (ROOT / ".github/workflows/cef-strict-platform-qualification.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("repository: microsoft/vcpkg", text)
        self.assertIn("ref: 9e593bb18ea69cc5095e012465dcd675a822ed0d", text)
        self.assertIn("repository: dobord/cef", text)
        self.assertIn("ref: 37efc4f9f340992d50d6f3fa41f617c9013fa26b", text)
        self.assertIn('>"$RUNNER_TEMP/cef-strict-native.log" 2>&1', text)
        self.assertNotIn("actions/cache", text)
        self.assertNotIn("upload-artifact", text)
        self.assertIn("gh api \"repos/dobord/vcpkg/actions/artifacts/$id/zip\"", text)
        self.assertIn("sha256sum -c -", text)
        self.assertIn('cat "$RUNNER_TEMP/cef-gn-evidence/gn-qualification.json"', text)
        self.assertNotIn("persist-credentials: true", text)
        self.assertIn("pkgconfig_module=", text)
        self.assertIn("missing_dependency=", text)

    def test_production_build_accepts_trusted_large_disk_runner_labels(self):
        text=(ROOT/'.github/workflows/build-release.yml').read_text()
        self.assertIn('runs-on: ${{ fromJSON(matrix.runner_labels) }}',text)
        self.assertIn("vars.CEF_STATIC_LINUX_RUNNER_LABELS || '[\"ubuntu-24.04\"]'",text)
        self.assertIn("vars.CEF_STATIC_WINDOWS_RUNNER_LABELS || '[\"windows-2022\"]'",text)
        self.assertNotIn('runs-on: ${{ matrix.os }}',text)

    def test_strict_engine_iteration_uploads_only_encrypted_checkpoint(self):
        workflow=(ROOT/'.github/workflows/cef-strict-engine-iteration.yml').read_text()
        worker=(ROOT/'secure_release/cef_strict_iteration.py').read_text()
        self.assertIn('ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55',workflow)
        self.assertIn('run: python -m secure_release.cef_strict_iteration',workflow)
        self.assertIn('- secure_release/cef_strict_iteration.py',workflow)
        self.assertIn('- ci/cef-strict-engine-lock.json',workflow)
        self.assertIn('Restore reviewed completed-package caches by exact artifact digest',workflow)
        self.assertIn('gh api "repos/dobord/vcpkg/actions/artifacts/$id/zip"',workflow)
        self.assertIn('sha256sum -c -',workflow)
        self.assertIn('VCPKG = "630ca19aa95016b4eb08fe4325e2b2df78fcca55"',worker)
        self.assertIn('CEF = "37efc4f9f340992d50d6f3fa41f617c9013fa26b"',worker)
        self.assertIn('"--binary-cache"',worker)
        self.assertIn('cef-strict-checkpoint-encrypted/*.enc',workflow)
        self.assertNotIn('path: ${{ runner.temp }}/cef-strict-checkpoint/*',workflow)
        self.assertIn('cef_cache.seal(',worker)
        self.assertIn('cef_cache.unseal(',worker)
        self.assertIn('check_run(',worker)
        self.assertIn('"cef-strict-engine-iteration.yml"',worker)
        self.assertIn('"cef-checkpoint", "linux"',worker)
        self.assertIn('"slice"',worker)
        self.assertIn('"restore"',worker)
        self.assertIn('"platform_build_inputs"',worker)
        self.assertIn('"third_party_modules_static"',worker)
        self.assertIn('"platform-graph-receipt.json"',worker)
        self.assertIn('"gn_graph_qualified"',worker)
        self.assertIn('"failure_stage"',worker)
        self.assertIn('"failure_category"',worker)
        self.assertIn('classify_private_log',worker)
        self.assertNotIn('print(text',worker)
        lock=(ROOT/'ci/cef-strict-engine-lock.json').read_text()
        self.assertIn('"checkpoint": null',lock)
        self.assertIn('"vcpkg_commit": "630ca19aa95016b4eb08fe4325e2b2df78fcca55"',lock)

    def test_sdk_dependency_qualification_keeps_private_build_logs_runner_local(self):
        text = (ROOT / ".github/workflows/cef-strict-sdk-deps.yml").read_text()
        self.assertIn("repository: dobord/lockfreecoro", text)
        self.assertIn("repository: dobord/lfc-ui", text)
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("persist-credentials: false", text)
        self.assertIn("sdk-deps-install.log", text)
        self.assertIn("sdk-deps-consumer-build.log", text)
        self.assertIn("SDK_DEPS_LINUX_QUALIFIED", text)
        self.assertIn("SDK_DEPS_WINDOWS_QUALIFIED", text)
        self.assertIn("SDK_DEPS_LINUX_INSTALL_FAILURE package=", text)
        self.assertIn("SDK_DEPS_WINDOWS_INSTALL_FAILURE package=", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP/sdk-deps", text)

    def test_combined_qualification_runs_only_for_explicit_checkpoint_lock(self):
        text=(ROOT/'.github/workflows/cef-strict-combined.yml').read_text()
        self.assertIn('workflow_dispatch:',text)
        self.assertIn('needs: gate',text)
        self.assertIn("if: needs.gate.outputs.ready == 'true'",text)
        self.assertIn('checkpoint\") is not None',text)
        self.assertIn('- .github/workflows/cef-strict-combined.yml',text)
        self.assertIn('- secure_release/cef_strict_combined.py',text)
        self.assertIn('- ci/cef-strict-engine-lock.json',text)
        self.assertIn('ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55',text)
        self.assertIn('run: python -m secure_release.cef_strict_combined',text)
        self.assertIn('cef-strict-combined-summary-',text)
        self.assertNotIn('cipher-output',text)
        self.assertNotIn('compiler.log',text)
        worker=(ROOT/'secure_release/cef_strict_combined.py').read_text()
        self.assertIn('VCPKG = "630ca19aa95016b4eb08fe4325e2b2df78fcca55"',worker)
        self.assertIn('CEF = "37efc4f9f340992d50d6f3fa41f617c9013fa26b"',worker)
        self.assertIn('freerdp_proxy_web_engine_view_cef.cpp',worker)
        self.assertIn('"lfc-ui-freerdp-cef-consumer"',worker)
        self.assertIn('freerdp-server-proxy',worker)
        self.assertIn('freerdp-shadow',worker)
        self.assertIn('-static-libstdc++ -static-libgcc',worker)
        self.assertIn('libavcodec',worker)
        self.assertIn('xvfb-run',worker)
        self.assertIn('openssl',worker)
        self.assertIn('[Server]',worker)
        self.assertIn('proxy_config.write_text',worker)
        self.assertIn('process.send_signal(signal.SIGTERM)',worker)
        self.assertIn('lfc_ui_freerdp_proxy_listener_verified',worker)

    def test_windows_msvc_stl_full_source_gate_builds_lfc_ui_example(self):
        text = (ROOT / ".github/workflows/cef-windows-source-msvc-stl.yml").read_text()
        self.assertIn("ref: 37efc4f9f340992d50d6f3fa41f617c9013fa26b", text)
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("source_build.py build", text)
        self.assertIn("export_static.py", text)
        self.assertIn("cef_cpp_support.lib", text)
        self.assertIn("use-installed-static-cef.patch", text)
        self.assertIn("--target web_engine_view_cef", text)
        self.assertIn("--coff-imports", text)
        self.assertIn("msvcp140.dll", text)
        self.assertIn("LFC_UI_WINDOWS_SOURCE_BUILT_STATIC_CEF_LINK_QUALIFIED", text)
        self.assertIn('private-vcpkg/.git', text)
        self.assertNotIn('Remove-Item -LiteralPath "$env:GITHUB_WORKSPACE/private-vcpkg" -Recurse -Force', text)
        self.assertNotIn("upload-artifact", text)

    def test_windows_msvc_stl_graph_gate_is_source_based_and_fail_closed(self):
        text = (ROOT / ".github/workflows/cef-windows-msvc-stl.yml").read_text()
        self.assertIn("ref: 139494aa73b6896b86b2b89230222bc4d9426b3e", text)
        self.assertIn("source_build.py prepare", text)
        self.assertIn("source_build.py check", text)
        self.assertIn("test_patch_source.py", text)
        self.assertIn("use_custom_libcxx", text)
        self.assertIn("v8_enable_sandbox", text)
        self.assertIn("CEF_WINDOWS_V8_SANDBOX_POLICY_NOT_EXPLICIT", text)
        self.assertIn("third_party/libc++", text)
        self.assertIn("static-link-inputs.json", text)
        self.assertIn("CEF_WINDOWS_MSVC_STL_GRAPH_QUALIFIED", text)
        self.assertNotIn("upload-artifact", text)

    def test_static_dependency_diagnostics_are_bounded_and_exact(self):
        text = (ROOT / ".github/workflows/static-dependency-diagnostics.yml").read_text()
        self.assertIn("ref: aaed4aa90086389b491b84db2a648e8e34a14266", text)
        self.assertIn("CEF_LIBUDEV_CONFIGURE_FAILURE cause=", text)
        self.assertIn("CEF_GTK3_CONFIGURE_FAILURE cause=", text)
        self.assertIn("cef-libudev", text)
        self.assertIn("gtk3", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP", text)

    def test_freerdp_static_diagnostic_uses_deterministic_audio_revision(self):
        text = (ROOT / ".github/workflows/freerdp-static-diagnostic.yml").read_text()
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("FREERDP_STATIC_CONFIGURE_FAILURE category=", text)
        self.assertNotIn("upload-artifact", text)

    def test_lfc_ui_static_freerdp_workflow_is_relocated_and_static(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-freerdp.yml").read_text()
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("'lfc-ui[freerdp]'", text)
        self.assertIn("freerdp-server-proxy", text)
        self.assertIn("freerdp-shadow", text)
        self.assertIn("LFC_UI_FREERDP_SHARED_TARGET_PAYLOAD", text)
        self.assertIn("-static-libstdc++ -static-libgcc", text)
        self.assertIn("LFC_UI_STATIC_FREERDP_QUALIFIED", text)
        self.assertIn("ffmpeg_dependency=", text)
        self.assertIn("buildtrees/ffmpeg", text)
        self.assertNotIn("upload-artifact", text)

    def test_strict_release_import_workflow_proves_fail_closed_rejection(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-cef.yml").read_text()
        self.assertIn("name: CEF strict release-import rejection", text)
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("ref: 37efc4f9f340992d50d6f3fa41f617c9013fa26b", text)
        self.assertIn('"profile": "static-third-party"', text)
        self.assertIn('"mode": "release-import"', text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn("CEF_STRICT_RELEASE_IMPORT_REJECTED", text)
        self.assertNotIn("LFC_UI_CEF_EXAMPLE_BUILD_FAILED", text)

    def test_current_private_source_contract_workflow_pins_gn_gate_revision(self):
        text = (ROOT / ".github/workflows/cef-strict-source-contracts.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("ref: 630ca19aa95016b4eb08fe4325e2b2df78fcca55", text)
        self.assertIn("ref: 37efc4f9f340992d50d6f3fa41f617c9013fa26b", text)
        self.assertIn("ref: 457fd41f39cbcff940c7af654da899d44ba5e553", text)
        self.assertNotIn("git -C private-vcpkg/.full-cef apply --check", text)
        self.assertNotIn("strict-import-cef", text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn('required_profile == "engine-static"', text)
        self.assertIn('strict_requalification_required": False', text)
        self.assertIn("test ! -e private-vcpkg/ports/cef-static/strict-windows-release-import.patch", text)
        self.assertIn("CEF::cpp", text)
        self.assertIn("cpp_support", text)
        self.assertIn("python -I -m unittest discover -s ci/cef-full/tests -v", text)
        self.assertIn("ci/cef-full/gn_check.py", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("actions/cache", text)


if __name__ == "__main__":
    unittest.main()
