"""Source-level guards for public-builder strict CEF qualification workflows."""
import json
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class StrictQualificationWorkflowTests(unittest.TestCase):
    def test_full_platform_workflow_is_exact_and_keeps_native_output_private(self):
        text = (ROOT / ".github/workflows/cef-strict-platform-qualification.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("group: cef-strict-platform-qualification-1873bb62", text)
        self.assertIn("ref: 9f1fdcf9294e8c125739ed425fa75dfb2c5ef459", text)
        self.assertIn("repository: microsoft/vcpkg", text)
        self.assertIn("ref: 9e593bb18ea69cc5095e012465dcd675a822ed0d", text)
        self.assertIn("repository: dobord/cef", text)
        self.assertIn("ref: 3b480cfbb460d2b761b84cecdc862aaaf8a38571", text)
        self.assertIn('>"$RUNNER_TEMP/cef-strict-native.log" 2>&1', text)
        self.assertNotIn("actions/cache", text)
        self.assertNotIn("upload-artifact", text)
        self.assertIn("gh api \"repos/dobord/vcpkg/actions/artifacts/$id/zip\"", text)
        self.assertIn("sha256sum -c -", text)
        self.assertIn('cat "$RUNNER_TEMP/cef-gn-evidence/gn-qualification.json"', text)
        self.assertNotIn("persist-credentials: true", text)
        self.assertIn("pkgconfig_module=", text)
        self.assertIn("missing_dependency=", text)
        self.assertIn("preflight_reason=", text)
        self.assertIn("preflight_stage=", text)
        self.assertIn("missing_library=", text)
        self.assertIn("runtime_module=", text)
        self.assertIn("CEF_GN_FAILURE category=", text)
        self.assertIn("external-archive", text)
        self.assertIn("clang-revision", text)
        self.assertIn("uncaptured-module", text)
        self.assertIn("header-metadata", text)
        self.assertIn("header-base", text)
        self.assertIn("missing-path", text)

    def test_production_build_accepts_trusted_large_disk_runner_labels(self):
        text=(ROOT/'.github/workflows/build-release.yml').read_text()
        self.assertIn('runs-on: ${{ fromJSON(matrix.runner_labels) }}',text)
        self.assertIn("vars.CEF_STATIC_LINUX_RUNNER_LABELS || '[\"ubuntu-24.04\"]'",text)
        self.assertIn("vars.CEF_STATIC_WINDOWS_RUNNER_LABELS || '[\"windows-2022\"]'",text)
        self.assertNotIn('runs-on: ${{ matrix.os }}',text)

    def test_strict_engine_iteration_uploads_only_encrypted_checkpoint(self):
        workflow=(ROOT/'.github/workflows/cef-strict-engine-iteration.yml').read_text()
        worker=(ROOT/'secure_release/cef_strict_iteration.py').read_text()
        isolation=(ROOT/'secure_release/cef_nss_isolation.py').read_text()
        self.assertIn('ref: b4bb281192ea8bb004542012ac804b988a4ff403',workflow)
        self.assertIn('run: python -m secure_release.cef_strict_iteration',workflow)
        self.assertIn('GITHUB_TOKEN: ${{ github.token }}',workflow)
        self.assertIn('group: cef-strict-engine-linux-1873bb62',workflow)
        self.assertIn('- secure_release/cef_strict_iteration.py',workflow)
        self.assertIn('- secure_release/cef_nss_isolation.py',workflow)
        self.assertIn('- ci/cef-strict-engine-lock.json',workflow)
        self.assertIn('Restore reviewed completed-package caches by exact artifact digest',workflow)
        self.assertIn('gh api "repos/dobord/vcpkg/actions/artifacts/$id/zip"',workflow)
        self.assertIn('sha256sum -c -',workflow)
        self.assertIn('VCPKG = "b4bb281192ea8bb004542012ac804b988a4ff403"',worker)
        self.assertNotIn('SDK_VCPKG =',worker)
        self.assertNotIn('verify_engine_registry_delta(',worker)
        self.assertIn('CEF = "2aff22e09daaa5c28780c5766a70ee13e61c93b6"',worker)
        self.assertIn('"--binary-cache"',worker)
        self.assertIn('cef-strict-checkpoint-encrypted/*.enc',workflow)
        self.assertNotIn('path: ${{ runner.temp }}/cef-strict-checkpoint/*',workflow)
        self.assertIn('cef_cache.seal(',worker)
        self.assertIn('cef_cache.unseal(',worker)
        self.assertIn('check_run(',worker)
        self.assertIn('GITHUB_TOKEN is required to restore reviewed strict checkpoint',worker)
        self.assertIn('"cef-strict-engine-iteration.yml"',worker)
        self.assertIn('"cef-checkpoint", "linux"',worker)
        self.assertIn('"slice"',worker)
        self.assertIn('"restore"',worker)
        self.assertIn('"platform_build_inputs"',worker)
        self.assertIn('"third_party_modules_static"',worker)
        self.assertIn('"platform-graph-receipt.json"',worker)
        self.assertIn('"gn_graph_qualified"',worker)
        self.assertIn('"failure_stage"',worker)
        self.assertIn('"failure_category"',worker)
        self.assertIn('classify_private_log',worker)
        self.assertIn('classify_compile_slice',worker)
        self.assertIn('"compile_failure_category"',worker)
        self.assertIn('"compile_failure_missing_header"',worker)
        self.assertIn('"compile_failure_uses_sysroot"',worker)
        self.assertIn('"compile_failure_sysroot_name"',worker)
        self.assertIn('"linker-duplicate-symbol"',worker)
        self.assertIn('"compile_failure_duplicate_symbols"',worker)
        self.assertIn('cef_nss_isolation.install(',worker)
        self.assertIn('CEF_NSS_SHA256_Update',isolation)
        self.assertIn('CEF_NSS_HMAC_Update',isolation)
        self.assertIn('CEF_NSS_CMAC_Update',isolation)
        self.assertIn('llvm-objcopy',isolation)
        self.assertIn('ninja.cef-real',isolation)
        self.assertIn('Frozen cef-nss archive changed before symbol isolation',isolation)
        self.assertIn('data = ninja.read_bytes()',isolation)
        self.assertIn('temporary_ninja.write_bytes(updated)',isolation)
        self.assertIn('references <= 0',isolation)
        self.assertIn('CHROMIUM_SYSROOT_AMD64',worker)
        self.assertIn('"52d61d4446ffebfaa3dda2cd02da4ab4876ff237853f46d273e7f9b666652e1d"',worker)
        self.assertIn('"usr/include/X11/Xlib-xcb.h"',worker)
        self.assertIn('"install-sysroot.py"',worker)
        self.assertIn('"--arch=amd64"',worker)
        self.assertIn('"sysroot_repaired"',worker)
        self.assertIn('"sysroot_header_verified"',worker)
        self.assertIn('CHROMIUM = "79460ebecaa5625e57a5fb679a735659e73dc687"',worker)
        self.assertIn('ensure_dawn_static_x11_headers(',worker)
        self.assertIn('DAWN_X11_PATCH_MARKER',worker)
        self.assertIn('DAWN_X11_PATCH_MARKER_V1',worker)
        self.assertIn('dawn_component("native")',worker)
        self.assertIn('cef_static_platform_prefix + "/include"',worker)
        self.assertIn('"dawn_x11_component_headers_verified"',worker)
        self.assertIn('"dawn_revision"',worker)
        self.assertIn('"dawn_x11_headers_verified"',worker)
        self.assertIn('value.get("failure_stage") == "compile-slice"',worker)
        self.assertIn('value.get("slice_state_present") is True',worker)
        self.assertIn('value.get("gn_graph_qualified") is not True',worker)
        self.assertIn('"--seconds", "9000", "--jobs", "2"',worker)
        self.assertNotIn('print(text',worker)
        lock=json.loads((ROOT/'ci/cef-strict-engine-lock.json').read_text())
        self.assertEqual(lock['schema'], 1)
        self.assertEqual(lock['platform'], 'linux')
        self.assertEqual(lock['vcpkg_commit'], 'b4bb281192ea8bb004542012ac804b988a4ff403')
        self.assertEqual(lock['cef_recipe_commit'], '2aff22e09daaa5c28780c5766a70ee13e61c93b6')
        checkpoint=lock['checkpoint']
        self.assertIsInstance(checkpoint, dict)
        self.assertEqual(set(checkpoint), {
            'run', 'attempt', 'producer_sha', 'artifact_id', 'artifact_sha256',
            'summary_artifact_id', 'summary_artifact_sha256', 'build_key', 'platform_sha256'
        })
        self.assertGreater(checkpoint['run'], 0)
        self.assertEqual(checkpoint['attempt'], 1)
        self.assertGreater(checkpoint['artifact_id'], 0)
        self.assertGreater(checkpoint['summary_artifact_id'], 0)
        self.assertRegex(checkpoint['producer_sha'], r'^[0-9a-f]{40}$')
        for name in ('artifact_sha256', 'summary_artifact_sha256', 'build_key', 'platform_sha256'):
            self.assertRegex(checkpoint[name], r'^[0-9a-f]{64}$')

    def test_sdk_dependency_qualification_keeps_private_build_logs_runner_local(self):
        text = (ROOT / ".github/workflows/cef-strict-sdk-deps.yml").read_text()
        self.assertIn("repository: dobord/lockfreecoro", text)
        self.assertIn("repository: dobord/lfc-ui", text)
        self.assertIn("ref: 39dccd415da14d8051559d66069019475d95787c", text)
        self.assertIn("persist-credentials: false", text)
        self.assertIn("sdk-deps-install.log", text)
        self.assertIn("sdk-deps-consumer-build.log", text)
        self.assertIn("SDK_DEPS_LINUX_QUALIFIED", text)
        self.assertIn("SDK_DEPS_WINDOWS_QUALIFIED", text)
        self.assertIn("SDK_DEPS_LINUX_INSTALL_FAILURE package=", text)
        self.assertIn("SDK_DEPS_WINDOWS_INSTALL_FAILURE package=", text)
        self.assertIn("SDK_DEPS_WINDOWS_SHARED_TARGET_PAYLOAD count=", text)
        self.assertIn(" names=", text)
        self.assertIn("'lfc-ui[lockfreecoro]'", text)
        self.assertNotIn("lfc-ui[atspi,lockfreecoro,opengl,vulkan]", text)
        self.assertNotIn("lfc-ui[lockfreecoro,opengl,vulkan]", text)
        self.assertNotIn("'dbus[core]'", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP/sdk-deps", text)

    def test_combined_qualification_runs_only_for_explicit_checkpoint_lock(self):
        text=(ROOT/'.github/workflows/cef-strict-combined.yml').read_text()
        self.assertIn('workflow_dispatch:',text)
        self.assertIn('needs: gate',text)
        self.assertIn("if: needs.gate.outputs.ready == 'true'",text)
        self.assertIn('checkpoint\") is not None',text)
        self.assertIn('ci/cef-strict-combined-lock.json',text)
        self.assertIn("CEF_STRICT_COMBINED_CHECKPOINT_REQUIRED",text)
        self.assertIn('- .github/workflows/cef-strict-combined.yml',text)
        self.assertIn('- secure_release/cef_strict_combined.py',text)
        self.assertIn('- secure_release/cef_nss_isolation.py',text)
        self.assertIn('- ci/cef-strict-combined-lock.json',text)
        self.assertIn('ref: 936bbb0e7cb7d6d10f8f5ef5874521466278c799',text)
        self.assertIn('ref: b4bb281192ea8bb004542012ac804b988a4ff403',text)
        self.assertIn('path: private-engine-vcpkg',text)
        self.assertIn('run: python -m secure_release.cef_strict_combined',text)
        self.assertIn('cef-strict-combined-summary-',text)
        self.assertNotIn('cipher-output',text)
        self.assertNotIn('compiler.log',text)
        worker=(ROOT/'secure_release/cef_strict_combined.py').read_text()
        self.assertIn('ENGINE_VCPKG = "b4bb281192ea8bb004542012ac804b988a4ff403"',worker)
        self.assertIn('SDK_VCPKG = "936bbb0e7cb7d6d10f8f5ef5874521466278c799"',worker)
        self.assertIn('if ENGINE_VCPKG == SDK_VCPKG:',worker)
        self.assertIn('Unified strict registry snapshots differ',worker)
        self.assertIn('reviewed lfc-ui/FreeRDP dependency delta',worker)
        self.assertIn('static-shadow-winpr-tools-dependency.patch',worker)
        self.assertIn('"port-version": 24',worker)
        self.assertIn('"git-tree": "aceadca1288983390522864e4d6c42b38ae84a6a"',worker)
        self.assertIn('["ffmpeg", "proxy", "x11"]',worker)
        self.assertIn('verify_engine_registry_delta(engine_registry, registry)',worker)
        self.assertIn('"cef-strict-combined-lock.json"',worker)
        self.assertIn('allow_resumable=False',worker)
        self.assertIn('ensure_chromium_sysroot(',worker)
        self.assertIn('ensure_dawn_static_x11_headers(',worker)
        self.assertIn('cef_nss_isolation.install(',worker)
        self.assertIn('cef_nss_isolation.record_receipt(',worker)
        self.assertIn('"engine-sysroot-preflight"',worker)
        self.assertIn('verify_relocated_metadata(',worker)
        self.assertIn('"producer_sdk_roots_removed"',worker)
        self.assertIn('"relocated_metadata_verified"',worker)
        self.assertIn('shutil.rmtree(installed)',worker)
        self.assertIn('shutil.rmtree(export_root)',worker)
        self.assertIn('"engine_vcpkg_commit": ENGINE_VCPKG',worker)
        self.assertIn('"sdk_vcpkg_commit": SDK_VCPKG',worker)
        self.assertIn('CEF = "2aff22e09daaa5c28780c5766a70ee13e61c93b6"',worker)
        self.assertIn('LFC_UI = "307afeab287b283514e036aa82ea1bd331dbac2a"',worker)
        self.assertIn('ports/lfc-ui/portfile.cmake',worker)
        self.assertIn('ci/release-plan.json',worker)
        self.assertIn('freerdp_proxy_web_engine_view_cef.cpp',worker)
        self.assertIn('canonical_proxy_example',worker)
        self.assertIn('lfc_ui_freerdp_cef_example_source_sha256',worker)
        self.assertIn('share/lfc-ui/examples/freerdp-proxy-cef',worker)
        self.assertIn('lfc_ui_freerdp_cef_installed_example_verified',worker)
        self.assertIn('Installed FreeRDP/CEF example differs from the pinned lfc-ui source',worker)
        self.assertIn('Installed FreeRDP/CEF example project lost its static SDK contract',worker)
        self.assertNotIn('(proxy_source / "CMakeLists.txt").write_text',worker)
        self.assertIn('lfc_ui / "examples/freerdp_proxy_web_engine_view_cef.cpp"',worker)
        self.assertNotIn('(proxy_source / "freerdp_proxy_web_engine_view_cef.cpp").write_text',worker)
        self.assertIn('"lfc-ui-freerdp-cef-consumer"',worker)
        self.assertIn('freerdp-server-proxy',worker)
        self.assertIn('freerdp-shadow',worker)
        self.assertIn('-static-libstdc++ -static-libgcc',worker)
        self.assertIn('libavcodec',worker)
        self.assertIn('"lfc-ui-freerdp-cef-readelf.log"',worker)
        self.assertIn('"lfc_ui_freerdp_cef_dt_needed_count"',worker)
        self.assertIn('r"\\(NEEDED\\).*?Shared library:',worker)
        self.assertIn('xvfb-run',worker)
        self.assertIn('openssl',worker)
        self.assertIn('[Server]',worker)
        self.assertIn('proxy_config.write_text',worker)
        self.assertIn('process.send_signal(signal.SIGTERM)',worker)
        self.assertIn('lfc_ui_freerdp_proxy_listener_verified',worker)

    def test_windows_engine_iteration_is_dormant_encrypted_and_exact(self):
        workflow = (ROOT / ".github/workflows/cef-windows-engine-iteration.yml").read_text()
        worker = (ROOT / "secure_release/cef_windows_iteration.py").read_text()
        self.assertIn("workflow_dispatch:", workflow)
        self.assertIn("group: cef-windows-engine-iteration-1873bb62", workflow)
        self.assertIn("- .github/workflows/cef-windows-engine-iteration.yml", workflow)
        self.assertIn("- ci/cef-windows-engine-lock.json", workflow)
        self.assertNotIn("- secure_release/cef_windows_iteration.py", workflow)
        self.assertIn("ref: 39dccd415da14d8051559d66069019475d95787c", workflow)
        self.assertIn("ref: 03abd124ebe3b8a57fb78470a75b5aa3ce064e31", workflow)
        self.assertIn("cef-windows-engine-checkpoint-encrypted/*.enc", workflow)
        self.assertNotIn("cef-windows-engine-work/**", workflow)
        self.assertIn('VCPKG = "39dccd415da14d8051559d66069019475d95787c"', worker)
        self.assertIn('CEF = "03abd124ebe3b8a57fb78470a75b5aa3ce064e31"', worker)
        self.assertIn('"cef-checkpoint", "windows"', worker)
        self.assertIn("cef_cache.seal(", worker)
        self.assertIn("cef_cache.unseal(", worker)
        self.assertIn('"slice"', worker)
        self.assertIn('"restore"', worker)
        self.assertIn('"source-prepare"', worker)
        self.assertIn('source_build.py", "prepare"', worker)
        self.assertIn("check_run(", worker)
        self.assertIn("runtime_verified", worker)
        self.assertIn("classify_private_failure", worker)
        self.assertIn('"failure_category"', worker)
        self.assertIn('"failure_token"', worker)
        self.assertIn("header_patterns", worker)
        self.assertIn('return "missing-header", name', worker)
        lock = (ROOT / "ci/cef-windows-engine-lock.json").read_text()
        self.assertIn('"platform": "windows"', lock)
        self.assertIn('"vcpkg_commit": "39dccd415da14d8051559d66069019475d95787c"', lock)
        self.assertIn('"cef_recipe_commit": "03abd124ebe3b8a57fb78470a75b5aa3ce064e31"', lock)
        self.assertIn('"checkpoint": null', lock)

    def test_windows_msvc_stl_full_source_gate_builds_lfc_ui_example(self):
        text = (ROOT / ".github/workflows/cef-windows-source-msvc-stl.yml").read_text()
        self.assertIn("ref: 3b480cfbb460d2b761b84cecdc862aaaf8a38571", text)
        self.assertIn("ref: 9f1fdcf9294e8c125739ed425fa75dfb2c5ef459", text)
        self.assertIn("source_build.py build", text)
        self.assertIn("group: cef-windows-msvc-stl-source-build-1873bb62", text)
        self.assertIn("export_static.py", text)
        self.assertIn("cef_cpp_support.lib", text)
        self.assertIn("use-installed-static-cef.patch", text)
        self.assertIn("--target web_engine_view_cef", text)
        self.assertIn("--coff-imports", text)
        self.assertIn("msvcp140.dll", text)
        self.assertIn("LFC_UI_WINDOWS_SOURCE_BUILT_STATIC_CEF_LINK_QUALIFIED", text)
        self.assertIn('private-vcpkg/.git', text)
        self.assertNotIn('Remove-Item -LiteralPath "$env:GITHUB_WORKSPACE/private-vcpkg" -Recurse -Force', text)
        self.assertNotIn("upload-artifact", text)

    def test_windows_msvc_stl_graph_gate_is_source_based_and_fail_closed(self):
        text = (ROOT / ".github/workflows/cef-windows-msvc-stl.yml").read_text()
        self.assertIn("ref: 139494aa73b6896b86b2b89230222bc4d9426b3e", text)
        self.assertIn("source_build.py prepare", text)
        self.assertIn("source_build.py check", text)
        self.assertIn("test_patch_source.py", text)
        self.assertIn("use_custom_libcxx", text)
        self.assertIn("v8_enable_sandbox", text)
        self.assertIn("CEF_WINDOWS_V8_SANDBOX_POLICY_NOT_EXPLICIT", text)
        self.assertIn("third_party/libc++", text)
        self.assertIn("static-link-inputs.json", text)
        self.assertIn("CEF_WINDOWS_MSVC_STL_GRAPH_QUALIFIED", text)
        self.assertNotIn("upload-artifact", text)

    def test_static_dependency_diagnostics_are_bounded_and_exact(self):
        text = (ROOT / ".github/workflows/static-dependency-diagnostics.yml").read_text()
        self.assertIn("ref: aaed4aa90086389b491b84db2a648e8e34a14266", text)
        self.assertIn("CEF_LIBUDEV_CONFIGURE_FAILURE cause=", text)
        self.assertIn("CEF_GTK3_CONFIGURE_FAILURE cause=", text)
        self.assertIn("cef-libudev", text)
        self.assertIn("gtk3", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP", text)

    def test_freerdp_v23_relocated_client_is_pkgconfig_independent(self):
        text = (ROOT / ".github/workflows/freerdp-relocated-client.yml").read_text()
        self.assertIn("ref: b4bb281192ea8bb004542012ac804b988a4ff403", text)
        self.assertIn("'freerdp[client,urbdrc]'", text)
        self.assertIn("-DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE", text)
        self.assertIn("FreeRDP::libusb-static", text)
        self.assertIn("libudev.a;libusb-1.0.a", text)
        self.assertIn("FREERDP_V23_RELOCATED_CLIENT_LINK_QUALIFIED", text)
        self.assertIn("cmake_minimum_required(VERSION 3.31)", text)
        self.assertIn("target_link_libraries(static_usb_probe PRIVATE FreeRDP::libusb-static)", text)
        self.assertIn("libusb_init", text)
        self.assertIn("udev_new", text)
        self.assertIn("FREERDP_V23_INSTALL_FAILURE package=", text)
        self.assertIn(" category=", text)
        self.assertIn("terminal_log=", text)
        self.assertIn("patch_name=", text)
        self.assertIn("patch_file=", text)
        self.assertIn("patch_reason=", text)
        self.assertNotIn("upload-artifact", text)

    def test_freerdp_static_diagnostic_uses_deterministic_audio_revision(self):
        text = (ROOT / ".github/workflows/freerdp-static-diagnostic.yml").read_text()
        self.assertIn("ref: c47b1b3cae1b2291b558ec674f61d653614ff637", text)
        self.assertIn("FREERDP_STATIC_CONFIGURE_FAILURE package=", text)
        self.assertIn(" category=", text)
        self.assertIn('"WITH_CAIRO"', text)
        self.assertIn('key.lower() + "=" + match.group(1).lower()', text)
        self.assertIn("cmake_source=", text)
        self.assertIn("link_target=", text)
        self.assertIn("missing_library=", text)
        self.assertIn("undefined_symbol=", text)
        self.assertIn("multiple_symbol=", text)
        self.assertIn("link_spec_target=", text)
        self.assertIn("ninja_link_target=", text)
        self.assertIn("link_spec_source=build.ninja", text)
        self.assertIn("reported_logs=", text)
        self.assertIn("terminal_log=", text)
        self.assertIn('"CMakeScratch"', text)
        self.assertIn('"CMakeTmp"', text)
        self.assertIn('part.startswith("TryCompile")', text)
        self.assertIn("link_library_count=", text)
        self.assertIn("link_libraries_tail=", text)
        self.assertIn("link_xcb_index=", text)
        self.assertIn("link_missing_index=", text)
        self.assertIn("freerdp_log=", text)
        self.assertIn("diagnostic_text = text", text)
        self.assertIn("text[max(boundaries):] if boundaries", text)
        self.assertIn("freerdp-terminal-ninja.log", text)
        self.assertIn("ninja_replay=yes", text)
        self.assertIn("FREERDP_RELOCATED_CLIENT_CONFIG_QUALIFIED", text)
        self.assertIn("FREERDP_RELOCATED_CLIENT_CONFIG_NEEDS_PKG_CONFIG_PATH", text)
        self.assertIn("FREERDP_RELOCATED_CLIENT_CONFIG_FAILURE category=", text)
        self.assertIn("PKG_CONFIG_LIBDIR=", text)
        self.assertIn('category = "patch-error"', text)
        self.assertIn("patch_name=", text)
        self.assertIn("patch_file=", text)
        self.assertIn("patch_reason=", text)
        self.assertIn('root.glob("patch-*-err.log")', text)
        self.assertIn("failed_outputs=", text)
        self.assertIn("failed_link_output=", text)
        self.assertIn("failed_link_libraries_tail=", text)
        self.assertIn("failed_library_count=", text)
        self.assertIn('("libusb", ("usb-1.0", "libusb-1.0"))', text)
        self.assertIn('("udev", ("udev",))', text)
        self.assertIn('("freerdp_client", ("freerdp-client3", "freerdp-client"))', text)
        self.assertIn('"failed_" + label + "_index="', text)
        self.assertIn('item.endswith(".a")', text)
        self.assertIn('base[3:-2]', text)
        self.assertIn("replay_text[failed[-1]:]", text)
        self.assertNotIn("upload-artifact", text)

    def test_lfc_ui_freerdp_regression_workflow_is_relocated_and_static(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-freerdp.yml").read_text()
        self.assertIn("ref: 936bbb0e7cb7d6d10f8f5ef5874521466278c799", text)
        self.assertIn("'lfc-ui[freerdp]'", text)
        self.assertIn("ref: 307afeab287b283514e036aa82ea1bd331dbac2a", text)
        self.assertIn("name: lfc-ui FreeRDP regression qualification", text)
        self.assertIn("Final product integration is qualified by Strict CEF combined SDK qualification", text)
        self.assertIn("lfc-ui[cef,freerdp,lockfreecoro]", text)
        self.assertIn("freerdp-server-proxy", text)
        self.assertIn("freerdp-shadow", text)
        self.assertIn("LFC_UI_FREERDP_SHARED_TARGET_PAYLOAD", text)
        self.assertIn("-static-libstdc++ -static-libgcc", text)
        self.assertIn("cmake_minimum_required(VERSION 3.31)", text)
        self.assertIn("actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c", text)
        self.assertIn("-r build-tools.lock", text)
        self.assertIn("LFC_UI_CMAKE_TOOL_QUALIFIED", text)
        self.assertIn('category = "cmake-version"', text)
        self.assertIn('details.append("cmake_required=" + cmake_version.group(1))', text)
        self.assertIn('details.append("cmake_running=" + cmake_version.group(2))', text)
        self.assertNotIn("cmake_minimum_required(VERSION 3.32)", text)
        self.assertIn("LFC_UI_STATIC_FREERDP_QUALIFIED", text)
        self.assertEqual(text.count("- name: Link relocated FreeRDP proxy and server probe"), 1)
        self.assertEqual(text.count("LFC_UI_STATIC_FREERDP_QUALIFIED"), 1)
        self.assertEqual(text.count("export lfc-ui freerdp ffmpeg"), 1)
        self.assertIn("LFC_UI_FREERDP_FFMPEG_PACKAGE_MISSING", text)
        self.assertIn("LFC_UI_FREERDP_UNEXPECTED_DVD_GRAPH", text)
        self.assertIn("LFC_UI_FREERDP_FFMPEG_OPTION_DISABLED", text)
        self.assertIn("grep -Eq '^Package: ffmpeg$'", text)
        self.assertIn("grep -Eq '^Package: libdvdcss$'", text)
        self.assertIn("WITH_FFMPEG:BOOL=ON", text)
        self.assertIn("export lfc-ui freerdp ffmpeg", text)
        self.assertIn("category=", text)
        self.assertIn("missing_target=", text)
        self.assertIn("missing_pkgconfig=", text)
        self.assertIn("cmake_source=", text)
        self.assertIn("lfcui_terminal_log=", text)
        self.assertIn('buildtrees / (package if package != "unknown" else "lfc-ui")', text)
        self.assertIn('diagnostic_text = terminal_text +', text)
        self.assertIn('cmake_not_found = re.search', text)
        self.assertIn('referenced_target = re.search', text)
        self.assertIn("LFC_UI_FREERDP_NONRELOCATABLE_METADATA", text)
        self.assertIn("LFC_UI_FREERDP_PRODUCER_INSTALL_ROOT_PRESENT", text)
        self.assertIn('rm -rf "$installed"', text)
        self.assertIn("lfc-ui-freerdp-readelf.log", text)
        self.assertIn("LFC_UI_FREERDP_DT_NEEDED names=", text)
        self.assertIn("LFC_UI_FREERDP_SHARED_RUNTIME_DEPENDENCY names=", text)
        self.assertIn("LFC_UI_FREERDP_HARFBUZZ_CXX_RUNTIME_LEAK", text)
        self.assertIn("lfc-ui-freerdp-probe-build.log", text)
        self.assertNotIn("upload-artifact", text)

    def test_strict_release_import_workflow_proves_fail_closed_rejection(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-cef.yml").read_text()
        self.assertIn("name: CEF strict release-import rejection", text)
        self.assertIn("ref: 39dccd415da14d8051559d66069019475d95787c", text)
        self.assertIn("ref: 03abd124ebe3b8a57fb78470a75b5aa3ce064e31", text)
        self.assertIn('"profile": "static-third-party"', text)
        self.assertIn('"mode": "release-import"', text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn("CEF_STRICT_RELEASE_IMPORT_REJECTED", text)
        self.assertIn("exit 0", text)
        self.assertNotIn("LFC_UI_CEF_EXAMPLE_BUILD_FAILED", text)

    def test_current_private_source_contract_workflow_pins_gn_gate_revision(self):
        text = (ROOT / ".github/workflows/cef-strict-source-contracts.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("ref: b4bb281192ea8bb004542012ac804b988a4ff403", text)
        self.assertIn("ref: 2aff22e09daaa5c28780c5766a70ee13e61c93b6", text)
        self.assertIn("ref: 457fd41f39cbcff940c7af654da899d44ba5e553", text)
        self.assertNotIn("git -C private-vcpkg/.full-cef apply --check", text)
        self.assertNotIn("strict-import-cef", text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn('required_profile == "engine-static"', text)
        self.assertIn('strict_requalification_required": False', text)
        self.assertIn("test ! -e private-vcpkg/ports/cef-static/strict-windows-release-import.patch", text)
        self.assertIn("CEF::cpp", text)
        self.assertIn("cpp_support", text)
        self.assertIn("python -I -m unittest discover -s ci/cef-full/tests -v", text)
        self.assertIn("ci/cef-full/gn_check.py", text)
        self.assertIn("test_platform_contract.py", text)
        self.assertIn("test_platform_gn.py", text)
        self.assertIn("test_patch_source.py", text)
        self.assertIn('"lfc-ui[cef,freerdp,lockfreecoro]" in packages', text)
        self.assertIn('"cef-static[strict-platform]" in packages', text)
        self.assertIn('"lfc-ui[freerdp]" not in packages', text)
        self.assertIn("STRICT_CEF_COMBINED_LFC_UI_FEATURE_SET_QUALIFIED", text)
        self.assertIn("test_native_regressions.py", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("actions/cache", text)


if __name__ == "__main__":
    unittest.main()
