"""Source-level guards for public-builder strict CEF qualification workflows."""
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class StrictQualificationWorkflowTests(unittest.TestCase):
    def test_full_platform_workflow_is_exact_and_keeps_native_output_private(self):
        text = (ROOT / ".github/workflows/cef-strict-platform-qualification.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("ref: 1eeb9d01ad078310bd2a3cf69a8e0983e21e8065", text)
        self.assertIn("repository: microsoft/vcpkg", text)
        self.assertIn("ref: 9e593bb18ea69cc5095e012465dcd675a822ed0d", text)
        self.assertIn("repository: dobord/cef", text)
        self.assertIn("ref: 8e76fadd560bc192484bad16427338fee8f632b7", text)
        self.assertIn('>"$RUNNER_TEMP/cef-strict-native.log" 2>&1', text)
        self.assertNotIn("actions/cache", text)
        self.assertNotIn("upload-artifact", text)
        self.assertIn("gh api \"repos/dobord/vcpkg/actions/artifacts/$id/zip\"", text)
        self.assertIn("sha256sum -c -", text)
        self.assertIn('cat "$RUNNER_TEMP/cef-gn-evidence/gn-qualification.json"', text)
        self.assertNotIn("persist-credentials: true", text)
        self.assertIn("pkgconfig_module=", text)
        self.assertIn("missing_dependency=", text)
        self.assertIn("preflight_reason=", text)
        self.assertIn("preflight_stage=", text)
        self.assertIn("missing_library=", text)
        self.assertIn("runtime_module=", text)

    def test_production_build_accepts_trusted_large_disk_runner_labels(self):
        text=(ROOT/'.github/workflows/build-release.yml').read_text()
        self.assertIn('runs-on: ${{ fromJSON(matrix.runner_labels) }}',text)
        self.assertIn("vars.CEF_STATIC_LINUX_RUNNER_LABELS || '[\"ubuntu-24.04\"]'",text)
        self.assertIn("vars.CEF_STATIC_WINDOWS_RUNNER_LABELS || '[\"windows-2022\"]'",text)
        self.assertNotIn('runs-on: ${{ matrix.os }}',text)

    def test_strict_engine_iteration_uploads_only_encrypted_checkpoint(self):
        workflow=(ROOT/'.github/workflows/cef-strict-engine-iteration.yml').read_text()
        worker=(ROOT/'secure_release/cef_strict_iteration.py').read_text()
        self.assertIn('ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691',workflow)
        self.assertIn('run: python -m secure_release.cef_strict_iteration',workflow)
        self.assertIn('- secure_release/cef_strict_iteration.py',workflow)
        self.assertIn('- ci/cef-strict-engine-lock.json',workflow)
        self.assertIn('Restore reviewed completed-package caches by exact artifact digest',workflow)
        self.assertIn('gh api "repos/dobord/vcpkg/actions/artifacts/$id/zip"',workflow)
        self.assertIn('sha256sum -c -',workflow)
        self.assertIn('VCPKG = "5fbfa70caed6db333018a66f3e7ff08c508e6691"',worker)
        self.assertNotIn('SDK_VCPKG =',worker)
        self.assertNotIn('verify_engine_registry_delta(',worker)
        self.assertIn('CEF = "8e76fadd560bc192484bad16427338fee8f632b7"',worker)
        self.assertIn('"--binary-cache"',worker)
        self.assertIn('cef-strict-checkpoint-encrypted/*.enc',workflow)
        self.assertNotIn('path: ${{ runner.temp }}/cef-strict-checkpoint/*',workflow)
        self.assertIn('cef_cache.seal(',worker)
        self.assertIn('cef_cache.unseal(',worker)
        self.assertIn('check_run(',worker)
        self.assertIn('"cef-strict-engine-iteration.yml"',worker)
        self.assertIn('"cef-checkpoint", "linux"',worker)
        self.assertIn('"slice"',worker)
        self.assertIn('"restore"',worker)
        self.assertIn('"platform_build_inputs"',worker)
        self.assertIn('"third_party_modules_static"',worker)
        self.assertIn('"platform-graph-receipt.json"',worker)
        self.assertIn('"gn_graph_qualified"',worker)
        self.assertIn('"failure_stage"',worker)
        self.assertIn('"failure_category"',worker)
        self.assertIn('classify_private_log',worker)
        self.assertNotIn('print(text',worker)
        lock=(ROOT/'ci/cef-strict-engine-lock.json').read_text()
        self.assertIn('"checkpoint": null',lock)
        self.assertIn('"vcpkg_commit": "5fbfa70caed6db333018a66f3e7ff08c508e6691"',lock)

    def test_sdk_dependency_qualification_keeps_private_build_logs_runner_local(self):
        text = (ROOT / ".github/workflows/cef-strict-sdk-deps.yml").read_text()
        self.assertIn("repository: dobord/lockfreecoro", text)
        self.assertIn("repository: dobord/lfc-ui", text)
        self.assertIn("ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691", text)
        self.assertIn("persist-credentials: false", text)
        self.assertIn("sdk-deps-install.log", text)
        self.assertIn("sdk-deps-consumer-build.log", text)
        self.assertIn("SDK_DEPS_LINUX_QUALIFIED", text)
        self.assertIn("SDK_DEPS_WINDOWS_QUALIFIED", text)
        self.assertIn("SDK_DEPS_LINUX_INSTALL_FAILURE package=", text)
        self.assertIn("SDK_DEPS_WINDOWS_INSTALL_FAILURE package=", text)
        self.assertIn("SDK_DEPS_WINDOWS_SHARED_TARGET_PAYLOAD count=", text)
        self.assertIn(" names=", text)
        self.assertIn("'lfc-ui[lockfreecoro]'", text)
        self.assertNotIn("lfc-ui[atspi,lockfreecoro,opengl,vulkan]", text)
        self.assertNotIn("lfc-ui[lockfreecoro,opengl,vulkan]", text)
        self.assertNotIn("'dbus[core]'", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP/sdk-deps", text)

    def test_combined_qualification_runs_only_for_explicit_checkpoint_lock(self):
        text=(ROOT/'.github/workflows/cef-strict-combined.yml').read_text()
        self.assertIn('workflow_dispatch:',text)
        self.assertIn('needs: gate',text)
        self.assertIn("if: needs.gate.outputs.ready == 'true'",text)
        self.assertIn('checkpoint\") is not None',text)
        self.assertIn("CEF_STRICT_COMBINED_CHECKPOINT_REQUIRED",text)
        self.assertIn('- .github/workflows/cef-strict-combined.yml',text)
        self.assertIn('- secure_release/cef_strict_combined.py',text)
        self.assertIn('- ci/cef-strict-engine-lock.json',text)
        self.assertIn('ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691',text)
        self.assertIn('ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691',text)
        self.assertIn('path: private-engine-vcpkg',text)
        self.assertIn('run: python -m secure_release.cef_strict_combined',text)
        self.assertIn('cef-strict-combined-summary-',text)
        self.assertNotIn('cipher-output',text)
        self.assertNotIn('compiler.log',text)
        worker=(ROOT/'secure_release/cef_strict_combined.py').read_text()
        self.assertIn('ENGINE_VCPKG = "5fbfa70caed6db333018a66f3e7ff08c508e6691"',worker)
        self.assertIn('SDK_VCPKG = "5fbfa70caed6db333018a66f3e7ff08c508e6691"',worker)
        self.assertIn('if ENGINE_VCPKG == SDK_VCPKG:',worker)
        self.assertIn('Unified strict registry snapshots differ',worker)
        self.assertIn('verify_engine_registry_delta(engine_registry, registry)',worker)
        self.assertIn('"engine_vcpkg_commit": ENGINE_VCPKG',worker)
        self.assertIn('"sdk_vcpkg_commit": SDK_VCPKG',worker)
        self.assertIn('CEF = "8e76fadd560bc192484bad16427338fee8f632b7"',worker)
        self.assertIn('freerdp_proxy_web_engine_view_cef.cpp',worker)
        self.assertIn('canonical_proxy_example',worker)
        self.assertIn('lfc_ui_freerdp_cef_example_source_sha256',worker)
        self.assertIn('share/lfc-ui/examples/freerdp-proxy-cef',worker)
        self.assertIn('lfc_ui_freerdp_cef_installed_example_verified',worker)
        self.assertIn('Installed FreeRDP/CEF example differs from the pinned lfc-ui source',worker)
        self.assertIn('Installed FreeRDP/CEF example project lost its static SDK contract',worker)
        self.assertNotIn('(proxy_source / "CMakeLists.txt").write_text',worker)
        self.assertIn('lfc_ui / "examples/freerdp_proxy_web_engine_view_cef.cpp"',worker)
        self.assertNotIn('(proxy_source / "freerdp_proxy_web_engine_view_cef.cpp").write_text',worker)
        self.assertIn('"lfc-ui-freerdp-cef-consumer"',worker)
        self.assertIn('freerdp-server-proxy',worker)
        self.assertIn('freerdp-shadow',worker)
        self.assertIn('-static-libstdc++ -static-libgcc',worker)
        self.assertIn('libavcodec',worker)
        self.assertIn('xvfb-run',worker)
        self.assertIn('openssl',worker)
        self.assertIn('[Server]',worker)
        self.assertIn('proxy_config.write_text',worker)
        self.assertIn('process.send_signal(signal.SIGTERM)',worker)
        self.assertIn('lfc_ui_freerdp_proxy_listener_verified',worker)

    def test_windows_engine_iteration_is_dormant_encrypted_and_exact(self):
        workflow = (ROOT / ".github/workflows/cef-windows-engine-iteration.yml").read_text()
        worker = (ROOT / "secure_release/cef_windows_iteration.py").read_text()
        self.assertIn("workflow_dispatch:", workflow)
        self.assertIn("- .github/workflows/cef-windows-engine-iteration.yml", workflow)
        self.assertIn("- ci/cef-windows-engine-lock.json", workflow)
        self.assertNotIn("- secure_release/cef_windows_iteration.py", workflow)
        self.assertIn("ref: 20acf029a5fbf1eacb4e77a8de4d853e562e4aed", workflow)
        self.assertIn("ref: 755aa5db4bfb9e5ffd87dd4ee575ae75203d62ca", workflow)
        self.assertIn("cef-windows-engine-checkpoint-encrypted/*.enc", workflow)
        self.assertNotIn("cef-windows-engine-work/**", workflow)
        self.assertIn('VCPKG = "20acf029a5fbf1eacb4e77a8de4d853e562e4aed"', worker)
        self.assertIn('CEF = "755aa5db4bfb9e5ffd87dd4ee575ae75203d62ca"', worker)
        self.assertIn('"cef-checkpoint", "windows"', worker)
        self.assertIn("cef_cache.seal(", worker)
        self.assertIn("cef_cache.unseal(", worker)
        self.assertIn('"slice"', worker)
        self.assertIn('"restore"', worker)
        self.assertIn('"source-prepare"', worker)
        self.assertIn('source_build.py", "prepare"', worker)
        self.assertIn("check_run(", worker)
        self.assertIn("runtime_verified", worker)
        self.assertIn("classify_private_failure", worker)
        self.assertIn('"failure_category"', worker)
        self.assertIn('"failure_token"', worker)
        lock = (ROOT / "ci/cef-windows-engine-lock.json").read_text()
        self.assertIn('"platform": "windows"', lock)
        self.assertIn('"vcpkg_commit": "20acf029a5fbf1eacb4e77a8de4d853e562e4aed"', lock)
        self.assertIn('"cef_recipe_commit": "755aa5db4bfb9e5ffd87dd4ee575ae75203d62ca"', lock)
        self.assertIn('"checkpoint": null', lock)

    def test_windows_msvc_stl_full_source_gate_builds_lfc_ui_example(self):
        text = (ROOT / ".github/workflows/cef-windows-source-msvc-stl.yml").read_text()
        self.assertIn("ref: 755aa5db4bfb9e5ffd87dd4ee575ae75203d62ca", text)
        self.assertIn("ref: 20acf029a5fbf1eacb4e77a8de4d853e562e4aed", text)
        self.assertIn("source_build.py build", text)
        self.assertIn("export_static.py", text)
        self.assertIn("cef_cpp_support.lib", text)
        self.assertIn("use-installed-static-cef.patch", text)
        self.assertIn("--target web_engine_view_cef", text)
        self.assertIn("--coff-imports", text)
        self.assertIn("msvcp140.dll", text)
        self.assertIn("LFC_UI_WINDOWS_SOURCE_BUILT_STATIC_CEF_LINK_QUALIFIED", text)
        self.assertIn('private-vcpkg/.git', text)
        self.assertNotIn('Remove-Item -LiteralPath "$env:GITHUB_WORKSPACE/private-vcpkg" -Recurse -Force', text)
        self.assertNotIn("upload-artifact", text)

    def test_windows_msvc_stl_graph_gate_is_source_based_and_fail_closed(self):
        text = (ROOT / ".github/workflows/cef-windows-msvc-stl.yml").read_text()
        self.assertIn("ref: 139494aa73b6896b86b2b89230222bc4d9426b3e", text)
        self.assertIn("source_build.py prepare", text)
        self.assertIn("source_build.py check", text)
        self.assertIn("test_patch_source.py", text)
        self.assertIn("use_custom_libcxx", text)
        self.assertIn("v8_enable_sandbox", text)
        self.assertIn("CEF_WINDOWS_V8_SANDBOX_POLICY_NOT_EXPLICIT", text)
        self.assertIn("third_party/libc++", text)
        self.assertIn("static-link-inputs.json", text)
        self.assertIn("CEF_WINDOWS_MSVC_STL_GRAPH_QUALIFIED", text)
        self.assertNotIn("upload-artifact", text)

    def test_static_dependency_diagnostics_are_bounded_and_exact(self):
        text = (ROOT / ".github/workflows/static-dependency-diagnostics.yml").read_text()
        self.assertIn("ref: aaed4aa90086389b491b84db2a648e8e34a14266", text)
        self.assertIn("CEF_LIBUDEV_CONFIGURE_FAILURE cause=", text)
        self.assertIn("CEF_GTK3_CONFIGURE_FAILURE cause=", text)
        self.assertIn("cef-libudev", text)
        self.assertIn("gtk3", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("cat $RUNNER_TEMP", text)

    def test_freerdp_static_diagnostic_uses_deterministic_audio_revision(self):
        text = (ROOT / ".github/workflows/freerdp-static-diagnostic.yml").read_text()
        self.assertIn("ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691", text)
        self.assertIn("FREERDP_STATIC_CONFIGURE_FAILURE package=", text)
        self.assertIn(" category=", text)
        self.assertIn('"WITH_CAIRO"', text)
        self.assertIn('key.lower() + "=" + match.group(1).lower()', text)
        self.assertIn("cmake_source=", text)
        self.assertIn("link_target=", text)
        self.assertIn("missing_library=", text)
        self.assertIn("undefined_symbol=", text)
        self.assertIn("multiple_symbol=", text)
        self.assertIn("freerdp_log=", text)
        self.assertNotIn("upload-artifact", text)

    def test_lfc_ui_static_freerdp_workflow_is_relocated_and_static(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-freerdp.yml").read_text()
        self.assertIn("ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691", text)
        self.assertIn("'lfc-ui[freerdp]'", text)
        self.assertIn("freerdp-server-proxy", text)
        self.assertIn("freerdp-shadow", text)
        self.assertIn("LFC_UI_FREERDP_SHARED_TARGET_PAYLOAD", text)
        self.assertIn("-static-libstdc++ -static-libgcc", text)
        self.assertIn("LFC_UI_STATIC_FREERDP_QUALIFIED", text)
        self.assertIn("ffmpeg_dependency=", text)
        self.assertIn("buildtrees/ffmpeg", text)
        self.assertNotIn("upload-artifact", text)

    def test_strict_release_import_workflow_proves_fail_closed_rejection(self):
        text = (ROOT / ".github/workflows/lfc-ui-static-cef.yml").read_text()
        self.assertIn("name: CEF strict release-import rejection", text)
        self.assertIn("ref: 5fbfa70caed6db333018a66f3e7ff08c508e6691", text)
        self.assertIn("ref: 8e76fadd560bc192484bad16427338fee8f632b7", text)
        self.assertIn('"profile": "static-third-party"', text)
        self.assertIn('"mode": "release-import"', text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn("CEF_STRICT_RELEASE_IMPORT_REJECTED", text)
        self.assertIn("exit 0", text)
        self.assertNotIn("LFC_UI_CEF_EXAMPLE_BUILD_FAILED", text)

    def test_current_private_source_contract_workflow_pins_gn_gate_revision(self):
        text = (ROOT / ".github/workflows/cef-strict-source-contracts.yml").read_text()
        self.assertIn("repository: dobord/vcpkg", text)
        self.assertIn("ref: 20acf029a5fbf1eacb4e77a8de4d853e562e4aed", text)
        self.assertIn("ref: 755aa5db4bfb9e5ffd87dd4ee575ae75203d62ca", text)
        self.assertIn("ref: 457fd41f39cbcff940c7af654da899d44ba5e553", text)
        self.assertNotIn("git -C private-vcpkg/.full-cef apply --check", text)
        self.assertNotIn("strict-import-cef", text)
        self.assertIn("static-third-party requires a source-built CEF engine", text)
        self.assertIn('required_profile == "engine-static"', text)
        self.assertIn('strict_requalification_required": False', text)
        self.assertIn("test ! -e private-vcpkg/ports/cef-static/strict-windows-release-import.patch", text)
        self.assertIn("CEF::cpp", text)
        self.assertIn("cpp_support", text)
        self.assertIn("python -I -m unittest discover -s ci/cef-full/tests -v", text)
        self.assertIn("ci/cef-full/gn_check.py", text)
        self.assertNotIn("upload-artifact", text)
        self.assertNotIn("actions/cache", text)


if __name__ == "__main__":
    unittest.main()
