"""Versioned Tink envelope. Keys/nonces/primitives are generated by Tink, not us."""
from __future__ import annotations
import base64
import hashlib
import io
import json
import os
from pathlib import Path
import shutil
import struct
import tempfile
from typing import Any

MAGIC = b"VCPKGSE1"
MAX_HEADER = 16384
MAX_FILE = 12 * 1024**3


def canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False).encode("ascii")


def _unique(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON field")
        result[key] = value
    return result


def parse(data: bytes | str) -> Any:
    return json.loads(data, object_pairs_hook=_unique, parse_constant=lambda _: (_ for _ in ()).throw(ValueError("nonfinite JSON")))


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def unb64(text: str) -> bytes:
    return base64.b64decode(text, validate=True)


def digest(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def _tink():
    import tink
    from tink import hybrid, signature, streaming_aead
    hybrid.register()
    signature.register()
    streaming_aead.register()
    return tink, hybrid, signature, streaming_aead


def serialize(handle) -> str:
    from tink import json_proto_keyset_format, secret_key_access
    return json_proto_keyset_format.serialize(handle, secret_key_access.TOKEN)


def key(text: str):
    from tink import json_proto_keyset_format, secret_key_access
    _tink()
    return json_proto_keyset_format.parse(text, secret_key_access.TOKEN)


def public_text(private_text: str) -> str:
    return serialize(key(private_text).public_keyset_handle())


def fingerprint(public: str) -> str:
    # A public-only primitive rejects a private key accidentally supplied here.
    _, hybrid, _, _ = _tink()
    handle = key(public)
    handle.primitive(hybrid.HybridEncrypt)
    # Public keysets must not contain secret key material.
    from tink import json_proto_keyset_format
    normalized = json_proto_keyset_format.serialize_without_secret(handle)
    return hashlib.sha256(canonical(parse(normalized))).hexdigest()


def generate(kind: str) -> tuple[str, str]:
    tink, hybrid, signature, _ = _tink()
    template = (signature.signature_key_templates.ED25519 if kind == "sign" else
                hybrid.hybrid_key_templates.DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM)
    handle = tink.new_keyset_handle(template)
    return serialize(handle), serialize(handle.public_keyset_handle())


def sign(payload: dict, private: str) -> dict:
    _, _, signature, _ = _tink()
    data = canonical(payload)
    sig = key(private).primitive(signature.PublicKeySign).sign(b"vcpkg-request-v1\x00" + data)
    return {"payload": payload, "signature": b64(sig)}


def verify(document: dict, public: str) -> dict:
    _, _, signature, _ = _tink()
    if set(document) != {"payload", "signature"}:
        raise ValueError("invalid signed request")
    key(public).primitive(signature.PublicKeyVerify).verify(
        unb64(document["signature"]), b"vcpkg-request-v1\x00" + canonical(document["payload"]))
    return document["payload"]


def seal_message(data: bytes, public: str, context: dict) -> str:
    _, hybrid, _, _ = _tink()
    if len(data) > 24576:
        raise ValueError("request too large")
    return b64(key(public).primitive(hybrid.HybridEncrypt).encrypt(data, b"vcpkg-message-v1\x00" + canonical(context)))


def open_message(ciphertext: str, private: str, context: dict) -> bytes:
    _, hybrid, _, _ = _tink()
    if len(ciphertext) > 49152:
        raise ValueError("request too large")
    return key(private).primitive(hybrid.HybridDecrypt).decrypt(
        unb64(ciphertext), b"vcpkg-message-v1\x00" + canonical(context))


def _aad(header: dict) -> bytes:
    return b"vcpkg-stream-v1\x00" + canonical(header)


def encrypt_file(source: Path, target: Path, public: str, context: dict) -> None:
    tink, hybrid, _, streaming_aead = _tink()
    if source.stat().st_size > MAX_FILE or target.exists():
        raise ValueError("invalid file size or existing output")
    handle = tink.new_keyset_handle(streaming_aead.streaming_aead_key_templates.AES256_GCM_HKDF_1MB)
    ctx = canonical(context)
    wrapped = key(public).primitive(hybrid.HybridEncrypt).encrypt(
        serialize(handle).encode(), b"vcpkg-file-key-v1\x00" + ctx)
    header = {"version": 1, "context": context, "recipient": fingerprint(public), "wrapped": b64(wrapped)}
    header_bytes = canonical(header)
    if len(header_bytes) > MAX_HEADER:
        raise ValueError("header too large")
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".encrypt-", dir=target.parent)
    temporary = Path(name)
    try:
        with os.fdopen(fd, "wb") as raw:
            raw.write(MAGIC + struct.pack(">I", len(header_bytes)) + header_bytes)
            with handle.primitive(streaming_aead.StreamingAead).new_encrypting_stream(raw, _aad(header)) as encrypted:
                with source.open("rb") as plain:
                    shutil.copyfileobj(plain, encrypted, length=1024 * 1024)
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)


def read_header(stream) -> dict:
    if stream.read(len(MAGIC)) != MAGIC:
        raise ValueError("unsupported envelope")
    raw_len = stream.read(4)
    if len(raw_len) != 4:
        raise ValueError("truncated envelope")
    size = struct.unpack(">I", raw_len)[0]
    if not 1 <= size <= MAX_HEADER:
        raise ValueError("invalid header size")
    raw = stream.read(size)
    if len(raw) != size:
        raise ValueError("truncated header")
    header = parse(raw)
    if set(header) != {"version", "context", "recipient", "wrapped"} or header["version"] != 1 or canonical(header) != raw:
        raise ValueError("invalid envelope header")
    return header


def decrypt_file(source: Path, target: Path, private: str, expected: dict) -> None:
    _, hybrid, _, streaming_aead = _tink()
    if target.exists() or source.stat().st_size > MAX_FILE + 1024**2:
        raise ValueError("invalid decryption target")
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".decrypt-", dir=target.parent)
    temporary = Path(name)
    try:
        with source.open("rb") as encrypted, os.fdopen(fd, "wb") as output:
            header = read_header(encrypted)
            if header["context"] != expected or header["recipient"] != fingerprint(public_text(private)):
                raise ValueError("wrong context or recipient")
            serialized = key(private).primitive(hybrid.HybridDecrypt).decrypt(
                unb64(header["wrapped"]), b"vcpkg-file-key-v1\x00" + canonical(expected))
            primitive = key(serialized.decode()).primitive(streaming_aead.StreamingAead)
            count = 0
            with primitive.new_decrypting_stream(encrypted, _aad(header)) as plain:
                while chunk := plain.read(1024 * 1024):
                    count += len(chunk)
                    if count > MAX_FILE:
                        raise ValueError("plaintext too large")
                    output.write(chunk)
        # No consumer can see the final path before EOF authentication succeeds.
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)
